# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (Runs at 0:00 12:00 15:00 18:00 21:00 UTC+8 every day.)
  #schedule: [{cron: "0 4,7,10,13,16 * * *"}]
  schedule: [{cron: "0 14 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: Mundi-Xu
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Shanghai
          plugin_lines: yes
          plugin_people: yes
          plugin_people_limit: 24
          plugin_people_size: 28
          plugin_people_thanks: YourButterfly, Dawuge
          plugin_people_types: followers, following
          plugin_rss: yes
          plugin_rss_limit: 5
          plugin_rss_source: https://mundi-xu.github.io/atom.xml
          plugin_stars: yes
          plugin_stars_limit: 7
          repositories_forks: yes

  blog-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          
          filename: blog-metrics.*
          #config_padding: 0

          # Options
          user: Mundi-Xu
          template: terminal
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Shanghai
          #plugin_isocalendar: yes
          #plugin_isocalendar_duration: half-year
          plugin_lines: yes
          plugin_pagespeed: yes
          plugin_pagespeed_url: https://mundi-xu.github.io/
          plugin_repositories: 100
          plugin_repositories_affiliations: owner
          plugin_repositories_batch: 100
          plugin_repositories_forks: yes
          repositories_forks: yes
