# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (Runs at 0:00 12:00 15:00 18:00 21:00 UTC+8 every day.)
  # schedule: [{cron: "0 4,7,10,13,16 * * *"}]
  schedule: [{cron: "0 14 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: gh-metrics/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Mundi-Xu
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Shanghai
          plugin_rss: yes
          plugin_rss_limit: 5
          plugin_rss_source: https://mundi-xu.github.io/atom.xml
          # plugin_stars: yes
          # plugin_stars_limit: 5
          plugin_starlists: yes
          plugin_starlists_limit: 3
          plugin_people: yes
          plugin_people_limit: 96
          plugin_people_size: 28
          plugin_people_types: followers, following
          plugin_fortune: yes
          plugin_music: yes
          plugin_music_provider: youtube
          plugin_music_mode: playlist
          plugin_music_limit: 4
          plugin_music_playlist: https://music.youtube.com/playlist?list=PLs0Fa2ryrJmSYufnucsaI1ixj3HbBZDEw
  blog-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: gh-metrics/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: blog-metrics.svg
          user: Mundi-Xu
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Shanghai
          plugin_pagespeed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed_url: https://mundi-xu.github.io/
          plugin_pagespeed_detailed: true
          plugin_achievements: yes
          plugin_achievements_threshold: X
          plugin_achievements_display: compact
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_fortune: yes
          plugin_music: yes
          plugin_music_provider: youtube
          plugin_music_mode: playlist
          plugin_music_limit: 6
          plugin_music_playlist: https://music.youtube.com/playlist?list=PLs0Fa2ryrJmSYufnucsaI1ixj3HbBZDEw
          # plugin_16personalities: yes
          # plugin_16personalities_url: ${{ secrets.SIXTEEN_PERSONALITIES_URL }}
          # plugin_16personalities_sections: personality, traits, profile
          # plugin_16personalities_scores: no
